-- =============================================================
-- VetFlow – DDL das tabelas CORE (Sprint 3 – DevOps Tools & Cloud Computing)
-- Banco: PostgreSQL 16
--
-- Este arquivo é DOCUMENTAÇÃO do schema exigida pelo item 3.3 do
-- enunciado. Ele NÃO precisa ser executado manualmente: o schema real
-- é criado automaticamente pelo Flyway assim que o container da API
-- sobe e se conecta neste banco (migrations V1/V2/V3, com 2 pequenos
-- ajustes de sintaxe SQL para rodar em Postgres em vez de H2 — ver
-- db-patches/ e o Dockerfile). O conteúdo abaixo reflete exatamente
-- o schema resultante dessas migrations.
--
-- O vetflow-java (código-fonte) não é alterado em nenhum momento.
-- =============================================================

-- Tutores (donos dos pets)
CREATE TABLE cv_tutors (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    email       VARCHAR(255) NOT NULL UNIQUE,
    phone       VARCHAR(20)  NOT NULL,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL
);

COMMENT ON TABLE cv_tutors IS 'Tutores (donos) dos pets cadastrados na clínica';
COMMENT ON COLUMN cv_tutors.id IS 'Identificador único do tutor';
COMMENT ON COLUMN cv_tutors.email IS 'E-mail do tutor, único no sistema (também usado para login)';
COMMENT ON COLUMN cv_tutors.active IS 'Indica se o cadastro do tutor está ativo';

-- Clínicas veterinárias
CREATE TABLE cv_clinics (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200) NOT NULL,
    address     VARCHAR(500),
    phone       VARCHAR(20),
    email       VARCHAR(255),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL
);

COMMENT ON TABLE cv_clinics IS 'Clínicas veterinárias parceiras';

-- Pets, relacionados a cv_tutors via tutor_id (N:1)
CREATE TABLE cv_pets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    species     VARCHAR(20)  NOT NULL,
    breed       VARCHAR(100),
    birth_date  DATE         NOT NULL,
    weight_kg   DOUBLE PRECISION NOT NULL,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL,
    tutor_id    BIGINT       NOT NULL,
    CONSTRAINT fk_pet_tutor FOREIGN KEY (tutor_id) REFERENCES cv_tutors(id)
);

COMMENT ON TABLE cv_pets IS 'Pets cadastrados, relacionados a um tutor (cv_tutors)';
COMMENT ON COLUMN cv_pets.species IS 'Espécie do pet (ex.: DOG, CAT)';
COMMENT ON COLUMN cv_pets.tutor_id IS 'Referência ao tutor responsável (cv_tutors.id)';

-- Consultas/agendamentos, relacionados a cv_pets e cv_clinics
CREATE TABLE cv_appointments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id        BIGINT       NOT NULL,
    clinic_id     BIGINT       NOT NULL,
    scheduled_at  TIMESTAMP    NOT NULL,
    type          VARCHAR(20)  NOT NULL,
    notes         VARCHAR(1000),
    completed     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP    NOT NULL,
    CONSTRAINT fk_appt_pet    FOREIGN KEY (pet_id)    REFERENCES cv_pets(id),
    CONSTRAINT fk_appt_clinic FOREIGN KEY (clinic_id) REFERENCES cv_clinics(id)
);

COMMENT ON TABLE cv_appointments IS 'Consultas/agendamentos de um pet em uma clínica';

-- Vacinas aplicadas, relacionadas a cv_pets
CREATE TABLE cv_vaccines (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id        BIGINT       NOT NULL,
    vaccine_name  VARCHAR(100) NOT NULL,
    applied_at    DATE         NOT NULL,
    next_dose_at  DATE         NOT NULL,
    batch         VARCHAR(50),
    created_at    TIMESTAMP    NOT NULL,
    CONSTRAINT fk_vaccine_pet FOREIGN KEY (pet_id) REFERENCES cv_pets(id)
);

COMMENT ON TABLE cv_vaccines IS 'Histórico de vacinas aplicadas em cada pet';
COMMENT ON COLUMN cv_vaccines.next_dose_at IS 'Data prevista da próxima dose/reforço';

-- Medicamentos em uso, relacionados a cv_pets
CREATE TABLE cv_medications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id      BIGINT       NOT NULL,
    name        VARCHAR(100) NOT NULL,
    dosage      VARCHAR(100),
    frequency   VARCHAR(100),
    start_date  DATE         NOT NULL,
    end_date    DATE,
    status      VARCHAR(20)  NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    CONSTRAINT fk_med_pet FOREIGN KEY (pet_id) REFERENCES cv_pets(id)
);

COMMENT ON TABLE cv_medications IS 'Medicamentos prescritos/em uso por um pet';

-- Usuários de autenticação (login da API/app), 1:1 opcional com cv_tutors
CREATE TABLE vf_users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)  NOT NULL,
    email       VARCHAR(255)  NOT NULL UNIQUE,
    password    VARCHAR(255)  NOT NULL,
    role        VARCHAR(20)   NOT NULL,
    tutor_id    BIGINT,
    enabled     BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP     NOT NULL,
    CONSTRAINT fk_user_tutor FOREIGN KEY (tutor_id) REFERENCES cv_tutors(id)
);

COMMENT ON TABLE vf_users IS 'Contas de acesso à API (perfis TUTOR e VET), senha em hash bcrypt';
COMMENT ON COLUMN vf_users.role IS 'Perfil de acesso: TUTOR ou VET';

-- ── Massa de dados inicial (carregada automaticamente pelo Flyway) ──
-- Ver detalhe completo em db-patches/ (mesmo conteúdo do V3__seed_data.sql
-- original do vetflow-java): 2 tutores, 2 clínicas, 3 pets, 3 vacinas e
-- 2 usuários de login (1 VET + 1 TUTOR), usados nas evidências de CRUD
-- do vídeo demonstrativo.
