-- =============================================================
-- PATCH DE DEVOPS — NÃO É O ARQUIVO ORIGINAL DO REPOSITÓRIO vetflow-java
-- =============================================================
-- O vetflow-java não é alterado em nenhum momento. Este arquivo é uma
-- cópia do V1__base_schema.sql original com apenas 2 trocas de sintaxe
-- para ficar portável entre H2 (dev local) e PostgreSQL (nuvem):
--   - "BIGINT AUTO_INCREMENT PRIMARY KEY" (só H2/MySQL)
--     -> "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" (H2 2.x e Postgres 10+)
--   - "DOUBLE" (só H2) -> "DOUBLE PRECISION" (H2 e Postgres)
-- Nenhuma tabela, coluna ou dado foi adicionado/removido.
-- O Dockerfile substitui o arquivo original dentro do .jar já
-- compilado por este aqui, no build, via unzip/zip do BOOT-INF/classes.
-- =============================================================

-- V1: Estrutura base do VetFlow (tutores, pets, clínicas, agendamentos, vacinas, medicamentos)

CREATE TABLE cv_tutors (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    email       VARCHAR(255) NOT NULL UNIQUE,
    phone       VARCHAR(20)  NOT NULL,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL
);

CREATE TABLE cv_clinics (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200) NOT NULL,
    address     VARCHAR(500),
    phone       VARCHAR(20),
    email       VARCHAR(255),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL
);

CREATE TABLE cv_pets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    species     VARCHAR(20)  NOT NULL,
    breed       VARCHAR(100),
    birth_date  DATE         NOT NULL,
    weight_kg   DOUBLE PRECISION NOT NULL,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL,
    tutor_id    BIGINT       NOT NULL,
    CONSTRAINT fk_pet_tutor FOREIGN KEY (tutor_id) REFERENCES cv_tutors(id)
);

CREATE TABLE cv_appointments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id        BIGINT       NOT NULL,
    clinic_id     BIGINT       NOT NULL,
    scheduled_at  TIMESTAMP    NOT NULL,
    type          VARCHAR(20)  NOT NULL,
    notes         VARCHAR(1000),
    completed     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP    NOT NULL,
    CONSTRAINT fk_appt_pet    FOREIGN KEY (pet_id)    REFERENCES cv_pets(id),
    CONSTRAINT fk_appt_clinic FOREIGN KEY (clinic_id) REFERENCES cv_clinics(id)
);

CREATE TABLE cv_vaccines (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id        BIGINT       NOT NULL,
    vaccine_name  VARCHAR(100) NOT NULL,
    applied_at    DATE         NOT NULL,
    next_dose_at  DATE         NOT NULL,
    batch         VARCHAR(50),
    created_at    TIMESTAMP    NOT NULL,
    CONSTRAINT fk_vaccine_pet FOREIGN KEY (pet_id) REFERENCES cv_pets(id)
);

CREATE TABLE cv_medications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id      BIGINT       NOT NULL,
    name        VARCHAR(100) NOT NULL,
    dosage      VARCHAR(100),
    frequency   VARCHAR(100),
    start_date  DATE         NOT NULL,
    end_date    DATE,
    status      VARCHAR(20)  NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    CONSTRAINT fk_med_pet FOREIGN KEY (pet_id) REFERENCES cv_pets(id)
);
