-- =============================================================
-- PATCH DE DEVOPS — NÃO É O ARQUIVO ORIGINAL DO REPOSITÓRIO vetflow-java
-- Mesma troca de sintaxe do V1 (AUTO_INCREMENT -> GENERATED BY DEFAULT
-- AS IDENTITY), para rodar em PostgreSQL. Ver V1__base_schema.sql.
-- =============================================================

-- V2: Tabela de usuários (autenticação) com dois perfis: TUTOR e VET

CREATE TABLE vf_users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)  NOT NULL,
    email       VARCHAR(255)  NOT NULL UNIQUE,
    password    VARCHAR(255)  NOT NULL,
    role        VARCHAR(20)   NOT NULL,
    tutor_id    BIGINT,
    enabled     BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP     NOT NULL,
    CONSTRAINT fk_user_tutor FOREIGN KEY (tutor_id) REFERENCES cv_tutors(id)
);
